### ISSUE TITLE
require needs global

### ISSUE THREAD

**Issue by PAEz** [proog128/jswin#8]
I dont normally do the require thing, but thought Id give it a go.
Without global its a real pain and there no way to pollute the global from in the require/module/whateveritscalled.
You cant even pass in a global from the outside.

So looks like Ill stick with merger for now, but its going to get something like require now.
I loved the dependency thing more than anything and I think I can emulate that.

**Comment by proog128** [comment]
I am not sure if I understand you correctly. You want to manipulate the global object in module A from a function in module B? That should have worked, but it didn't because of a bug. I just fixed that, please try again. Here is an example:

``` javascript
// main.js
var foo = require("foo");

foo.appendBarToGlobal(this);

print(bar); // prints 42

// foo.js
exports.appendBarToGlobal = function(global) {
    global.bar = 42;
};
```

**Comment by PAEz** [comment]
Sweet that certainly helps and makes require worthwhile to me.
But in other things it seems the modules get a global variable inserted into them.  This would be much better because you wouldnt have to explicitly call a function on the module to pollute the global.  Plus some things just dont work without the global.  I couldnt get FastClass to work the require way, so Im just switching to Fiber which seems to work fine.
Oh well at least thats enough that its worth me using it all the time now, so Im off to change a bunch of code ;)
