### ISSUE TITLE
CreateWindowEx failed

### ISSUE THREAD

**Issue by PAEz** [proog128/jswin#9]
I just tried out the update (sweet!) and the windows stuff isnt working.
When I try to run winmain.js I get a dialog saying "CreateWindowEx failed".
I havent had a chance to really look at it (or the update) as Im mega busy.
Seems this prob has been around for a while aswell, but I havent done any gui stuff in a while.
I tried running it with some of the other releases and they didnt work either.
An old release does work tho.  Ive been using the same old one as I modded it to do themes and so didnt notice this error creep in.

**Comment by proog128** [comment]
Hi, thanks for testing! There was an issue in the handling of callback functions which should be fixed now.
